id: a9b2e05de41b4428a49e06252bfdac7a
initial_creation_type: ocr
source_metadata:
  volumes:
    2fb5ed5ed20a4c0c8c670d8df921346e:
      base_file: v087.txt
      image_group_id: I1PD95933
      title: འདུལ་བའི་མདོ།
      total_pages: 1560
      volume_number: 88
